Repository SeattleColleges/nsc-events-android, pull requests merged in 2023-07, with the labels that each got.

#6 Create dependabot.yml
  .github/dependabot.yml
Labels: Sprint 2

#8 feature 5 login page 01
  app/build.gradle
  app/src/main/java/com/example/nsc_events/MainActivity.kt
  app/src/main/java/com/example/nsc_events/Routes.kt
  app/src/main/java/com/example/nsc_events/screen/Login.kt
  app/src/main/java/com/example/nsc_events/screen/ScreenMain.kt
  app/src/main/java/com/example/nsc_events/screen/SignUp.kt
  app/src/main/java/com/example/nsc_events/ui/theme/Color.kt
  app/src/main/java/com/example/nsc_events/ui/theme/Theme.kt
  app/src/main/res/drawable/packaging.png
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#13 nsc-events-android-2-12-change-sdk-from-33-to-34
  app/build.gradle
Labels: bug

#17 nbc-events-2-17-remove-compose-dependency
  app/build.gradle
Labels: Sprint 2

#19 nsc-events-android-2-19-fix-compose-compiler-dependency-issues
  app/build.gradle
  build.gradle
Labels: Sprint 2

#25 included vars needed for apk signing in workflow
  .env.sample
Labels: enhancement
