Repository SeattleColleges/nsc-events-android, pull requests merged in 2023-12, with the labels that each got.

#152 nsc_android_feature_147_adminviewpage
  app/src/main/java/com/example/nsc_events/Routes.kt
  app/src/main/java/com/example/nsc_events/screen/AdminView.kt
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
  app/src/main/java/com/example/nsc_events/screen/ScreenMain.kt
Labels: Sprint 3

#176 nsc-events-android_5_171_login_page_finishing_tasks
  app/src/main/java/com/example/nsc_events/screen/Login.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 5

#179 nsc_events_android-01-homepage-finishing-tasks
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
Labels: Sprint 5

#183 nsc-events-android_5_178_complete-add-events-finishing-tasks
  app/src/main/java/com/example/nsc_events/screen/AddEvent.kt
Labels: enhancement, Sprint 5

#181 nsc-events-android-4-137-update-nsc-events-android-readme
  README.md
Labels: Sprint 4

#185 nsc-events-android_184_admin-creator-view-routing
  app/src/main/java/com/example/nsc_events/screen/Login.kt
Labels: enhancement, Sprint 5
