Repository SeattleColleges/nsc-events-android, pull requests merged in 2023-08, with the labels that each got.

#24 ignored all .env Excluded .env.sample from ignore
  .gitignore
Labels: enhancement

#28 Product functionality added
  app/build.gradle
  app/src/main/java/com/example/nsc_events/Routes.kt
  app/src/main/java/com/example/nsc_events/data/Event.kt
  app/src/main/java/com/example/nsc_events/screen/AddEvent.kt
  app/src/main/java/com/example/nsc_events/screen/Login.kt
  app/src/main/java/com/example/nsc_events/screen/ScreenMain.kt
Labels: enhancement, Sprint 4

#32 Updated Gradle plugin to 8.1.0
  build.gradle
Labels: dependencies

#34 Home Page Addition #29
  app/src/main/java/com/example/nsc_events/Routes.kt
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
  app/src/main/java/com/example/nsc_events/screen/Login.kt
  app/src/main/java/com/example/nsc_events/screen/ScreenMain.kt
Labels: enhancement, Sprint 5
