Repository SeattleColleges/nsc-events-android, pull requests merged in 2023-11, with the labels that each got.

#104 nsc-events-android-3-103-refactor-event-variable-names
  app/src/main/java/com/example/nsc_events/data/Event.kt
  app/src/main/java/com/example/nsc_events/screen/AddEvent.kt
Labels: Sprint 3

#87 Create input for Sign Up page
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
  app/src/main/java/com/example/nsc_events/screen/SignUp.kt
Labels: Sprint 2

#77 nsc-event-android-1-52-Event-DTO
  app/src/main/java/com/example/nsc_events/data/Event.kt
  app/src/main/java/com/example/nsc_events/screen/AddEvent.kt
Labels: Sprint 2

#100 Added topappbar to login.kt
  app/src/main/java/com/example/nsc_events/screen/Login.kt
Labels: Sprint 2

#113 nsc-events-android-3-112-update-yaml-file
  .github/workflows/on-pull-request.yml
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
Labels: bug, Sprint 3

#101 nsc-events-android-3-81-create_input_fields
  app/build.gradle
  app/src/main/java/com/example/nsc_events/data/Event.kt
  app/src/main/java/com/example/nsc_events/screen/AddEvent.kt
  app/src/main/res/drawable/nsc_logo.png
Labels: enhancement

#121 nsc-events-android-3-114-change-data-folder-structure
  app/build.gradle
  app/src/main/java/com/example/nsc_events/data/Datasource.kt
  app/src/main/java/com/example/nsc_events/model/Event.kt
  app/src/main/java/com/example/nsc_events/screen/AddEvent.kt
  app/src/main/java/com/example/nsc_events/screen/EventDetail.kt
Labels: Sprint 3

#106 nsc-events-android-3-75-create-edit-delete-attend-buttons
  app/src/androidTest/java/com/example/nsc_events/EventDetailTest.kt
  app/src/androidTest/java/com/example/nsc_events/HomePageTest.kt
  app/src/main/java/com/example/nsc_events/Routes.kt
  app/src/main/java/com/example/nsc_events/data/Datasource.kt
  app/src/main/java/com/example/nsc_events/model/Event.kt
  app/src/main/java/com/example/nsc_events/screen/AddEvent.kt
  app/src/main/java/com/example/nsc_events/screen/EventDetail.kt
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
  app/src/main/java/com/example/nsc_events/screen/ScreenMain.kt
  app/src/main/res/drawable/happy_thanksgiving.jpg
  app/src/main/res/drawable/newyears_png2.jpg
  app/src/main/res/drawable/speech_2759550__480_1_png.webp
  app/src/main/res/values/strings.xml
Labels: Sprint 3

#127 nsc_android_enhancement_125_connect_signup_function
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nsc_events/MainActivity.kt
  app/src/main/java/com/example/nsc_events/data/network/HttpRoutes.kt
  app/src/main/java/com/example/nsc_events/data/network/auth/SignUpService.kt
  app/src/main/java/com/example/nsc_events/data/network/auth/SignUpServiceImpl.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/auth_dto/SignUpRequest.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/auth_dto/SignUpResponse.kt
  app/src/main/java/com/example/nsc_events/screen/SignUp.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#120 nsc-events-adroid_sprint_2_issue_119_navigation_for_signup_page
  app/src/main/java/com/example/nsc_events/screen/SignUp.kt
  app/src/main/res/drawable/baseline_visibility_off_24.xml
  app/src/main/res/drawable/baseline_visibility_on_24.xml
Labels: enhancement, Sprint 2

#129 nsc_android-02-73-login_function
  app/src/main/java/com/example/nsc_events/data/network/auth/LoginService.kt
  app/src/main/java/com/example/nsc_events/data/network/auth/LoginServiceImpl.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/auth_dto/LoginRequest.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/auth_dto/LoginResponse.kt
  app/src/main/java/com/example/nsc_events/screen/Login.kt
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#144 nsc_android_enhancement_143_forgot-password
  app/src/main/java/com/example/nsc_events/data/network/auth/ForgotPasswordService.kt
  app/src/main/java/com/example/nsc_events/data/network/auth/ForgotPasswordServiceImpl.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/auth_dto/ForgotPasswordRequest.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/auth_dto/ForgotPasswordResponse.kt
  app/src/main/java/com/example/nsc_events/screen/ForgotPassword.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#154 NSC_Events_Sprint_4_Change_Colors_To_NSC_Theme_Colors
  app/src/main/java/com/example/nsc_events/ui/theme/Color.kt
  app/src/main/java/com/example/nsc_events/ui/theme/Theme.kt
Labels: Sprint 4

#149 Nsc events android 3 97 edit button
  app/src/main/java/com/example/nsc_events/Routes.kt
  app/src/main/java/com/example/nsc_events/screen/EventDetail.kt
  app/src/main/java/com/example/nsc_events/screen/EventEdit.kt
  app/src/main/java/com/example/nsc_events/screen/ScreenMain.kt
Labels: Sprint 3

#165 nsc-events-android_3_151_add-functionality-delete-button
  app/src/main/java/com/example/nsc_events/data/Datasource.kt
  app/src/main/java/com/example/nsc_events/data/network/HttpRoutes.kt
  app/src/main/java/com/example/nsc_events/data/network/auth/DeleteService.kt
  app/src/main/java/com/example/nsc_events/data/network/auth/DeleteServiceImpl.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/auth_dto/DeleteRequest.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/auth_dto/DeleteResponse.kt
  app/src/main/java/com/example/nsc_events/model/Event.kt
  app/src/main/java/com/example/nsc_events/screen/EventDetail.kt
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
  app/src/main/java/com/example/nsc_events/screen/Login.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Sprint 3
