Repository SeattleColleges/nsc-events-android, pull requests merged in 2024-02, with the labels that each got.

#195 nsc-andoird-02-194-edit_user_role_screen_creation
  app/src/main/java/com/example/nsc_events/Routes.kt
  app/src/main/java/com/example/nsc_events/data/Datasource.kt
  app/src/main/java/com/example/nsc_events/model/User.kt
  app/src/main/java/com/example/nsc_events/screen/AdminView.kt
  app/src/main/java/com/example/nsc_events/screen/EditUserRole.kt
  app/src/main/java/com/example/nsc_events/screen/ScreenMain.kt
  app/src/main/res/values/strings.xml
Labels: Sprint 2

#197 nsc-events-android-2-196-create-templates-for-android
  .github/issue.md
  .github/pull_request.md
  .github/user_story.md
Labels: Sprint 2

#199 nsc-events-android-add-front-matter-to-android
  .github/issue.md
  .github/pull_request.md
  .github/user_story.md
Labels: Sprint 2

#202 nsc-events-android_2_201_drop-down-menu
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
Labels: enhancement, Sprint 2

#204 nsc-events-android_2_203_remove-edit-login-buttons
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
Labels: enhancement, Sprint 2

#206 nsc-events-android-3-205-add-files-for-android
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/pull_request.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: Sprint 3
