Repository SeattleColleges/nsc-events-android, pull requests merged in 2024-04, with the labels that each got.

#210 nsc-events-android-209-fix-android-templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/pull_request.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: bug

#228 nsc-events-android_5_218_edit-delete-button-accessibility
  app/src/main/java/com/example/nsc_events/screen/EventDetail.kt
Labels: enhancement, Sprint 5

#227 nsceventsandroid_sprint5_226_removesignup
  README.md
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Sprint 5

#219 nsc-events-android_5_217_change-event-text-and-image
  app/src/main/java/com/example/nsc_events/screen/EventDetail.kt
Labels: enhancement, Sprint 5

#225 Nsc-events-android-223-create-event-page-fields-update-01
  app/src/main/java/com/example/nsc_events/data/Datasource.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/event_dto/EventRequest.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/event_dto/EventUpdateRequest.kt
  app/src/main/java/com/example/nsc_events/model/Event.kt
  app/src/main/java/com/example/nsc_events/screen/AddEvent.kt
Labels: enhancement, Sprint 5
