Repository SeattleColleges/nsc-events-android, pull requests merged in 2024-01, with the labels that each got.

#180 Nsc events android 4 169 attend button
  app/src/main/java/com/example/nsc_events/data/network/HttpRoutes.kt
  app/src/main/java/com/example/nsc_events/data/network/auth/AttendService.kt
  app/src/main/java/com/example/nsc_events/data/network/auth/AttendServiceImpl.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/auth_dto/AttendeeDto.kt
  app/src/main/java/com/example/nsc_events/screen/EventDetail.kt
  app/src/main/res/values/strings.xml
Labels: Sprint 4

#168 nsc_events_android-187-creating_an_event
  app/src/main/java/com/example/nsc_events/MainActivity.kt
  app/src/main/java/com/example/nsc_events/data/network/HttpRoutes.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/event_dto/EventDeleteResponse.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/event_dto/EventRequest.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/event_dto/EventResponse.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/event_dto/EventUpdateRequest.kt
  app/src/main/java/com/example/nsc_events/data/network/dto/event_dto/EventUpdateResponse.kt
  app/src/main/java/com/example/nsc_events/data/network/service/EventService.kt
  app/src/main/java/com/example/nsc_events/data/network/service/EventServiceImpl.kt
  app/src/main/java/com/example/nsc_events/model/DateSerializer.kt
  app/src/main/java/com/example/nsc_events/model/Event.kt
  app/src/main/java/com/example/nsc_events/screen/AddEvent.kt
Labels: enhancement

#191 nsc-events-android_2_189_miscellaneous-tasks
  app/src/main/java/com/example/nsc_events/screen/EventDetail.kt
  app/src/main/java/com/example/nsc_events/screen/HomePage.kt
Labels: enhancement, Sprint 2

#192 nsc-events-android_2_190_update-toast-message
  app/src/main/java/com/example/nsc_events/data/network/dto/auth_dto/SignUpRequest.kt
  app/src/main/java/com/example/nsc_events/screen/Login.kt
  app/src/main/java/com/example/nsc_events/screen/SignUp.kt
Labels: bug, Sprint 2
